on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Check linting
        run: bundle exec fastlane lintDebug

  unitTest:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Run unit tests
        run: bundle exec fastlane unitTest

  buildDebug:
    runs-on: ubuntu-latest
      needs: unitTest
      steps:
        - uses: actions/checkout@v2

        - name: Set up ruby env
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: 2.7.2
            bundler-cache: true

        - name: Build Debug apk
          run: bundle exec fastlane buildDebug

        - name: Upload build artifacts
            uses: actions/upload-artifact@v2
            with:
              name: assets
              path: |
                ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk

  buildRelease:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: unitTest
    steps:
      - uses: actions/checkout@v2

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v1
        id: android_keystore
        with:
          fileName: "key.jks"
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Build release apk
        run: bundle exec fastlane buildReleaseApk
        env:
          KEYSTORE_FILE: ${{ steps.android_keystore.outputs.filePath }}
          STORE_PASSWORD: ${{ secrets.PASSWORD }}
          KEY_ALIAS: ${{ secrets.ALIAS}}
          KEY_PASSWORD: ${{ secrets.PASSWORD }}

      - name: Build release bundle
        run: bundle exec fastlane buildReleaseAab
        env:
          KEYSTORE_FILE: ${{ steps.android_keystore.outputs.filePath }}
          STORE_PASSWORD: ${{ secrets.PASSWORD }}
          KEY_ALIAS: ${{ secrets.ALIAS}}
          KEY_PASSWORD: ${{ secrets.PASSWORD }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path: |
            ${{ github.workspace }}/app/build/outputs/bundle/release
            ${{ github.workspace }}/app/build/outputs/apk/release/app-release.apk